FROM node:20
WORKDIR /frontend

RUN corepack enable

COPY package.json pnpm-lock.yaml \
     tailwind.config.ts postcss.config.mjs next.config.mjs ./

RUN pnpm install

COPY . .

EXPOSE 3000
CMD ["pnpm", "dev"]
